a= int(input("Zadaj celé čislo a: "))
b= int(input("Zadaj celé čislo b: "))
print("----------------")
sucet= (a+b)
nasobok= (a*b)
delenie= (a/b)
delenie_celo=(a//b)
zvysok= (a%b)
priemer=((a+b)/2)
print(a, "+", b, "=", sucet)
print(a, "x", b, "=", nasobok)
print(a, ":", b, "=", delenie)
print(a, ":", b, "=", delenie_celo, "zv.", zvysok)
print("aritmeticky priemer", priemer)